spring:
  application:
    name: ejemplo-spring-boot-security-jwt-v2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
# configuración de jwt
app:
  # clave secreta de al menos 32 caracteres
  # Web generadora: https://jwtsecret.com/generate
  jwt-secret: 466e88c0a7b2664a58b0c4c7cd3085dbdd28c95310b147451d02395ee59800ff
  jwt-expiration-milliseconds: 86400000 # un día
  jwt-refresh-token-milliseconds: 604800000 # 7 días
